version: '3.7'
services:

  postgres:
    container_name: postgres-total
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${{secrets.POSTGRES_DB}}
      - POSTGRES_USER=${{secrets.POSTGRES_USER}}
      - POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
      - TZ=Asia/Seoul
    volumes:
      - "./init/:/docker-entrypoint-initdb.d"

  mongo:
    image: "mongo:latest"
    container_name: mongo-total
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${{secrets.MONGO_USERNAME}}
      - MONGO_INITDB_ROOT_PASSWORD=${{secrets.MONGO_PASSWORD}}

  redis:
    image: redis:latest
    container_name: redis-total
    ports:
      - 6380:6379