version: '3.7'
services:
  postgres:
    container_name: postgres-total
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=chatting-total
      - POSTGRES_USER=chatUSer
      - POSTGRES_PASSWORD=1234
      - TZ=Asia/Seoul
    volumes:
      - "./init/:/docker-entrypoint-initdb.d"

  mongo:
    image: "mongo:latest"
    container_name: mongo-total
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chatUser
      - MONGO_INITDB_ROOT_PASSWORD=1234

  redis:
    image: redis:latest
    container_name: redis-total
    ports:
      - 6379:6379
