spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/chatting-total
      driver-class-name: org.postgresql.Driver
      username: chatUser
      password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # sql 로깅
        highlight_sql: true # SQL 문 색 부여
        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
        dialect: org.hibernate.dialect.PostgreSQLDialect # Hibernate Dialect 추가

jwt:
  access:
    expiration-time: 1800
  refresh:
    expiration-time: 1209600000
  secret-key: mysecretkey
