spring:
  config:
    import:
      - classpath:application-secret.yml
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
    defer-datasource-initialization: true
    dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always


