spring:
  config:
    import:
      - classpath:application-secret.yml
      - optional:file:.env.properties

  datasource:
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: ${MONGO_URL}
      authentication-database: admin
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
