spring:
  profiles:
    default: dev

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
