spring:
  datasource:
    url: jdbc:h2:./data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # Hibernate가 테이블 자동 생성
    defer-datasource-initialization: true
    show-sql: true
    properties:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org:
      springframework:
        jdbc:
          datasource:
            init: DEBUG
        test:
          context:
            jdb: DEBUG

