spring:
  datasource:
    url: jdbc:h2:./data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  redis:
    host: localhost
    port: 54322
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.4

logging:
  level:
    de.flapdoodle.embed.mongo: DEBUG
    org.springframework.data.redis: DEBUG
    redis.embedded: DEBUG
