name: Java CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # docker deploy
      - name: Docker Deploy executing remote ssh commands using ssh_key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER}}
          key: ${{ secrets.SSH_KEY }}
          script: |
            
            cd /home/ubuntu/
            
            sudo touch /home/ubuntu/.env
            sudo echo "${{ secrets.ENV_VARS }}" | sudo tee /home/ubuntu/.env > /dev/null
            
            sudo touch docker-compose.yml
            echo "${{vars.DOCKER_COMPOSE}}" | sudo tee docker-compose.yml > /dev/null
            
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/linkupchat:latest
            sudo docker stop linkupchat || true
            sudo docker rm linkupchat || true
            docker-compose -f docker-compose.yml --env-file ./.env up -d
            sudo docker image prune -f